### ISSUE TITLE
version typo in mods.toml prevents the Loded mod from loading

### ISSUE THREAD

**Issue by four-hands-hold-this-key** [RecraftorsMC/Loded#1]
there is a typo in mods.toml where multiple right brackets are swapped with parentheses, causing the modpack to crash

![Screenshot 2024-11-25 005111](https://github.com/user-attachments/assets/b2d04694-8d92-405e-8fc5-9308514d900c)

fixing the typos resolved the issue

also the issue tracker url in there doesn't seem right?

**Comment by NerjalNosk** [comment]
Issue url does be wrong indeed. Might have copied the file from another project and made an oopsie.

However, parentheses are not an issue. They in fact indicate it as "such version an above", although it does indeed require a comma, which is missing in the minecraft dependency.

**Comment by NerjalNosk** [comment]
Fixed with [3d3d5819a8](https://codeberg.org/RecraftorsMC/loded/commit/3d3d5819a8a18371a6af30459ef2faaa77a4c719) (also sources migrated, while github issues will still receive support for now, it will be preferred for any further issue to be opened on codeberg)
